---
layout: post
title: Migration du blog
author: Alexis Hassler
tags: 
---

== De Blogger…

J'ai démarré ce blog en 2010 sur Blogger.
L'intérêt de la plateforme, c'était de pouvoir démarrer sans effort : rien à installer, rien à déployer et un minimum de configuration.

Le revers de la médaille, c'est que l'éditeur _WYSIWYG_ n'est pas très pratique pour un blog orienté développement, surtout pour les extraits de code.

Ça faisait des mois que j'envisageais de changer de plateforme, mais comme tout travail non prioritaire, je reportais au lendemain.
Cet été, j'ai enfin pris le temps de m'en occuper.

== … à Jekyll

Il existe pas mal d'alternatives à Blogger. 
La plus populaire est certainement Wordpress.
Il y a aussi plein de générateurs de sites statiques, et ça ça me plait bien.
Le principal intérêt, c'est pour le déploiement : un simple serveur Web, sans base de données ou runtime.

Parmi les générateur, il y a aussi pas mal de possibilités. 
J'ai choisi de ne pas trop chercher.
J'ai pris la une solution mainstream avec Jekyll.
<!--more-->

Certes ce n'est pas très hype, mais ça fait le boulot.
Et un gros écosysytème de plug-in permet de personnaliser le blog.

On peut même déployer sur Github Pages.

== Migration

En changeant de plateforme, je voulais conserver mes anciens billets, avec leurs URLs.
Pour ça, Blogger a une fonction d'export grâce à laquelle j'ai pu récupérer mon historique dans un fichier XML.
Ensuite, j'ai utilisé la commande d'import de Jekyll.

Ensuite, j'ai mis les mains dans le système de template de Jekyll, en Liquid, et dans le CSS.
J'arrive à quelque chose qui ressemble à la version précédente.
Je l'améliorerai quand j'aurai un peu de temps… dans quelques mois.

== Hébergerment

Comme je le soulignais plus haut, l'hébergerment est facile avec Jekyll :
on génère les pages statiques, qu'on dépose sur un serveur web, et voilà.

Plus simple encore, on peut utiliser Github Pages.
On pousse les articles bruts et c'est lui qui gère le build et la publication.
C'est très sympa mais il y a des contraintes ; on ne peut utiliser que certains plug-ins présélectionnés par Github.

Pour contourner ça, j'utilise deux repositories.
Le source est dans le premier repo, sur lequel j'ai branché un build Travis-CI.
En fin de build, Travis pousse les pages générées sur le repo de GH pages.
C'est un peu plus compliqué et plus long, mais j'ai ma publication automatique.

Au final, j'ai ajouté Cloudflare pour la gestion du domaine et du SSL.

== Cassé

Si vous lisez ce billet, c'est que ça marche !

J'ai quand même perdu des choses : recherche, tags, pages par année et par mois et commentaires.

C'est les commentaires qui manquent le plus, à la fois pour les informations qu'ils apportaient aux anciens articles et pour leur interactivité.

Même si je ne suis pas un grand fan de ce type de service (cf. ghostery), je vais certainement tester Disqus.
A moins que quelqu'un me propose une meilleure solution (sur twitter).

Pour la recherche, je laisse tomber.

Pour le reste, il y a un plug-in.